### PR TITLE
Set the filter in the content element

### PR DESCRIPTION
**Pull request by kozi**
Add the option to set the filter in the content element if module
newslist or newsarchive is selected codefog/contao-news_categories#48

### CODE REVIEW

**Comment by kozi** [comment]
Will you integrate this request?

**Comment by qzminski** [comment]
Yes, it should be merged this week.

**Comment by kozi** [comment]
Perfect. Thanks!

**Comment by qzminski** [comment]
Can you please test this branch and confirm everything's working fine? Afterwards I'll merge it to the develop branch.

Just please note that my improvements do not make use of the ```tl_content.module``` field anymore. The extension is now using ```tl_content.news_module``` instead.

https://github.com/codefog/contao-news_categories/tree/feature/filter-content-element

**Comment by kozi** [comment]
Looks good.
How can I configure the module to show no items if theres no new entry with the filter category? (The current implementation lists all items.)

**Comment by qzminski** [comment]
How do I reproduce this? Do you have an online demo by chance?

**Comment by kozi** [comment]
> How can I configure the module to show no items if theres no new entry with the filter category? (The current implementation lists all items.)
Tested the current implementation (develop-Branch) and everything is OK. Obviously it was a configuration error

**Comment by qzminski** [comment]
I hope this week, sir.

**Pull request merged**
