### PR TITLE
new rendering of cumulative filter (#178)

### LINKED ISSUE #178: new rendering of cumulative filter
new feature / enhancement of the cumulative filter:

- Display the categories and subcategories in a hierarchical way.
- Add a checkbox in front of each entry

(un-) select the checkboxes changes the filter.

example:
image

this maybe another solution for #173

### PR DESCRIPTION
**Pull request by arboc**
closes #178 

- refactoring code (do not repeat yourself)
- adding a new frontend module and  templates

### CODE REVIEW

**Comment by qzminski** [comment]
Thank you for contribution @arboc ! Can you allow the edit from maintainers for this PR please?

**Comment by arboc** [comment]
>  Can you allow the edit from maintainers for this PR please?

@qzminski how can I do that?

**Comment by qzminski** [comment]
It is described here: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by arboc** [comment]
@qzminski  I already saw that... but there is no option to allow edits...

image

**Comment by arboc** [comment]
@qzminski I gave you write access to my fork, I hope this helps

**Comment by qzminski** [comment]
Thanks, that worked and I have pushed my commit. Can you please double-check that the feature still works? I made tests locally and it seems it does, but just to be 100% sure 😉

**Comment by arboc** [comment]
tested with Contao 4.9 and php7.3... looks good.

**Comment by qzminski** [comment]
Thank you @arboc, I will release a new version 3.4.0 today.

**Pull request merged**
