### PR TITLE
news_sorted compatibility

### PR DESCRIPTION
**Pull request by fritzmg**
Simple (albeit not very pretty) way of making this extension compatible with the `news_sorted` extension.

### CODE REVIEW

**Comment by qzminski** [comment]
You have tested this and it works, right?

**Comment by qzminski** [comment]
Also, does `\news_sorted\ModuleNewsList` extend the original Contao class?

**Comment by fritzmg** [comment]
ad 1) yes, I tested this in Contao 4.4.0 and it works.

ad 2) no, it replaces the `\Contao\ModulesNewsList` completely unfortunately - which means that some features will not work (e.g. the `newsListCountItems` and `newsListFetchItems` hooks). However, this will be the case regardless of whether you (additionally) use `news_categories` or not.

**Comment by qzminski** [comment]
Just released 2.8.5, thanks!

**Comment by fritzmg** [comment]
Btw. may be I was a bit premature with this ;). I have developed another extension now that implements the functionality of the old news_sorted extension, but without replacing the news list module: [fritzmg/contao-news-sorting](https://github.com/fritzmg/contao-news-sorting). I didn't realize before, that there were already suitable hooks in place since Contao 3.5. Further more, this extension (currently) uses the same fields and values as my pull request for the contao/news-bundle: https://github.com/contao/news-bundle/pull/13

So may be in a future version you can drop the compatibility again.

**Comment by qzminski** [comment]
Heh okay let it sit there for now, should not harm anyone.

**Pull request merged**
