### PR TITLE
Support for Contao 5.1+

### PR DESCRIPTION
**Pull request by aschempp**
This should update the extension for Contao 5.1 support (only). I initially tried to keep Contao 4.13 compatibility, but that's almost impossible with the new feed page types and a lot of compatibility breaks. Not sure if this would be a new major version since we dropped several classes. They are not really API, but it also wouldn't harm (maybe we could refactor some more stuff).

PS: still a draft since it's all brain dump and not fully tested yet (especially the feed stuff).

### CODE REVIEW

**Comment by jankout** [comment]
That’s amazing and thank you very much for your great work, @aschempp 

how and when will it be published? @qzminski

**Comment by aschempp** [comment]
when its ready… 🤷 
https://www.terminal42.ch/en/open-source

**Comment by aschempp** [comment]
I just noticed removing the picker widget might mean this would be a new major version. Which means I could remove some dead code and deprecations. What do you think @qzminski, should we have a new major or re-add the widget?

**Comment by qzminski** [comment]
Have a new major definitely 😄

**Comment by aschempp** [comment]
very well then 🙃 I removed the deprecated stuff and updated everything to using autowiring and attributes 😎

**Comment by aschempp** [comment]
I think this is ready for release (RC or stable). I even added a new CI chain (see https://github.com/aschempp/contao-news_categories/actions) 😎

**Comment by qzminski** [comment]
Released as 4.0.0. Thanks a lot @aschempp !

**Comment by jankout** [comment]
Thank you very much @aschempp for your great work.

**Pull request merged**
